"""
Pydantic models for structured LLM outputs.

These models replace fragile `json.loads()` parsing with type-safe 
Pydantic validation, used with `LangChainLLM.generate_structured()`.
"""

from pydantic import BaseModel, Field
from typing import List, Optional


class ValidationResult(BaseModel):
    """Result of the query validation step (gatekeeper)."""
    is_valid: bool = Field(
        description="Whether the query is relevant to the biomedical domain"
    )
    refusal_message: Optional[str] = Field(
        default=None,
        description="Polite refusal message if query is invalid"
    )
    reasoning: Optional[str] = Field(
        default=None,
        description="Brief reasoning for the validation decision"
    )


class ExecutionStep(BaseModel):
    """A single step in the execution plan."""
    id: int = Field(description="Unique step identifier")
    agent: str = Field(description="Agent name to execute this step")
    input: str = Field(description="Refined query/input for the agent")
    dependency: Optional[List[int]] = Field(
        default=None,
        description="IDs of steps this step depends on"
    )


class ExecutionGroup(BaseModel):
    """A group of steps that execute together (parallel or sequential)."""
    group_id: int = Field(description="Unique group identifier")
    mode: str = Field(
        description="Execution mode: 'parallel' or 'sequential'"
    )
    steps: List[ExecutionStep] = Field(
        description="Steps in this execution group"
    )


class ExecutionPlan(BaseModel):
    """The complete execution plan generated by the planner LLM."""
    execution_groups: List[ExecutionGroup] = Field(
        description="Ordered list of execution groups"
    )
    reasoning: Optional[str] = Field(
        default=None,
        description="Reasoning for this execution plan"
    )
